name = "fragrances-catalog-worker"
main = "src/index.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MASTER_DB"
bucket_name = "komanda-master-db"

[[r2_buckets]]
binding = "IMAGES_DB"
bucket_name = "fragrances-images"

[[workflows]]
name = "fragrances-catalog-workflow"
binding = "CATALOG_WORKFLOW"
class_name = "CatalogWorkflow"

[limits]
cpu_ms = 300000

[triggers]
crons = ["*/30 * * * *"]
