name = "komanda-sync-worker"
main = "src/index.js"
compatibility_date = "2025-01-01"

[[r2_buckets]]
binding = "MASTER_DB"
bucket_name = "komanda-master-db"

[limits]
subrequests = 10000
cpu_ms = 300000

[triggers]
crons = ["*/30 * * * *"]
