name = "fragrances-catalog"
main = "src/index.js"
compatibility_date = "2025-05-05"
compatibility_flags = ["nodejs_compat"]

[[r2_buckets]]
binding = "MASTER_DB"
bucket_name = "komanda-master-db"

[[r2_buckets]]
binding = "IMAGES_DB"
bucket_name = "fragrances-images"

[[workflows]]
name = "fragrances-catalog-workflow"
binding = "CATALOG_WORKFLOW"
class_name = "CatalogWorkflow"

[[d1_databases]]
binding = "CATALOG_DB"
database_name = "fragrances-catalog-db"
database_id = "1713638f-2116-40c7-ac71-976a0f5f6b27"

[limits]
cpu_ms = 300000

[triggers]
crons = ["*/30 * * * *"]
